SELECT * FROM (
    SELECT 
        CAR.CAR_ID, 
        CAR.CAR_TYPE,
        ROUND(((CAR.DAILY_FEE*30) * (100-DISCOUNT_RATE) / 100), 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR CAR
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN ON CAR.CAR_TYPE = PLAN.CAR_TYPE
    WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
      AND CAR.CAR_ID NOT IN (
        SELECT HIS.CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS
        WHERE HIS.START_DATE <= '2022-11-30'
          AND HIS.END_DATE >= '2022-11-01'
      )
      AND PLAN.DURATION_TYPE = '30일 이상'
    ) AS TMP
WHERE FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC